import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


DRIVE_ROOT = (
    Path.home()
    / "Library"
    / "CloudStorage"
    / "GoogleDrive-fernandoreisdasilva@gmail.com"
    / "Meu Drive"
)
PRODUCTION_ROOT = DRIVE_ROOT / "AYL_Production"
DEFAULT_JOB_ID = "TEST_WARDROBE_WAN_0001"
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "video_base"
MODEL_FAMILY = "Wan 2.7 image-to-video via Replicate Web"
FALLBACK_MODEL_FAMILY = "Wan 2.1 image-to-video via Replicate Web"
TARGET_STATUS = "draft"
ELIGIBLE_WARDROBE_STATUSES = {"approved", "needs_review"}
VALID_STATUSES = {
    "draft",
    "ready_for_next_stage",
    "in_progress",
    "needs_review",
    "approved",
    "blocked",
    "returned_for_revision",
    "final",
    "archived",
}


PROMPT_TEMPLATE = """TASK
Create a short Wan 2.7 image-to-video base clip from the supplied wardrobe image.

MODEL FAMILY
Wan 2.7 image-to-video via Replicate Web

FALLBACK
Use Wan 2.1 image-to-video via Replicate Web only if Wan 2.7 is unavailable.

SOURCE IMAGE
{source_image_path}

TARGET
Duration: 4-5 seconds.
Shot type: stable talking-head base.
Motion: minimal natural presenter stillness only, loop-friendly.
Mouth: closed or neutral unless the model offers explicit audio/lip-sync readiness controls.
Use case: future audio and lip-sync pipeline readiness.

IDENTITY LOCK
Preserve Luca's exact identity from the source image.
Preserve face shape, age impression, skin tone, hairline, hairstyle, eyes, nose, mouth, jawline, facial proportions, and body proportions.
Keep the outfit, framing, lighting, and clean educational visual package consistent with the source image.
Do not make Luca look like a different person.

VISUAL PACKAGE
visual_package: {visual_package}
thumbnail_style: {thumbnail_style}
primary_character: {character_id}

WARDROBE TEST
outfit_id: {outfit_id}
description: {description}
test_goal: {test_goal}

MOTION DIRECTION
Keep head and shoulders mostly still.
Allow only subtle breathing, tiny posture settling, and very small eye blinks.
Keep hands out of frame or still if visible.
No gesturing.
No head turns.
No camera movement.
No zoom.
No dramatic expression change.
No mouth opening.

BACKGROUND AND OUTPUT
Clean simple educational background.
No text.
No logos.
No extra people.
No new props.
No flags or national symbols.
No motion blur.
No distorted face, teeth, hands, or clothing edges.
Produce a stable, loop-friendly base clip suitable for later audio/lip-sync review.
"""


REVIEW_TEMPLATE = """# Wan 2.7 Review - {job_id}

Model family: Wan 2.7 image-to-video via Replicate Web
Fallback model family: Wan 2.1 image-to-video via Replicate Web
Target: short 4-5 second stable talking-head base, minimal motion, identity preserved, loop-friendly, audio/lip-sync readiness if available.

Official status values:
draft, ready_for_next_stage, in_progress, needs_review, approved, blocked, returned_for_revision, final, archived

## Scoring

Use 0-5 for each category.

| video_id | character_id | wardrobe_status | video_status | identity_stability | face_stability | mouth_neutrality | body_motion | loopability | lip_sync_readiness | review_notes |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
{review_rows}

## Criteria

identity_stability 0-5: same Luca identity throughout the clip.
face_stability 0-5: no warping, flicker, melting, or face replacement.
mouth_neutrality 0-5: mouth remains closed or neutral, with no accidental speech.
body_motion 0-5: minimal presenter stillness, no large gestures or camera movement.
loopability 0-5: start/end are calm enough for reuse or trimming.
lip_sync_readiness 0-5: clean face, stable framing, and neutral mouth suitable for later lip-sync.

## Notes

Generated by scripts/video_base/create_wan27_test_prompts.py.
No media files are copied into git; source_image_path and output_path are external references/placeholders.
"""


def default_queue_path(job_id: str) -> Path:
    return (
        PRODUCTION_ROOT
        / "04_video_jobs"
        / job_id
        / "wardrobe"
        / "wardrobe_test_queue.json"
    )


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def load_result_record(wardrobe_root: Path, outfit_id: str) -> dict:
    result_path = wardrobe_root / "results" / f"{outfit_id}_result.json"
    if not result_path.exists():
        return {}
    return load_json(result_path)


def coalesce(*values: object) -> str:
    for value in values:
        if isinstance(value, str) and value.strip():
            return value
    return ""


def get_source_image_path(outfit: dict, result_record: dict) -> str:
    return coalesce(
        result_record.get("result_path"),
        result_record.get("source_image_path"),
        result_record.get("image_path"),
        outfit.get("result_path"),
        outfit.get("source_image_path"),
        outfit.get("image_path"),
        outfit.get("generated_image_path"),
    )


def prompt_filename(video_id: str) -> str:
    return f"{video_id}_wan27_prompt.txt"


def build_video_record(
    queue: dict,
    outfit: dict,
    result_record: dict,
    prompts_root: Path,
    outputs_root: Path,
) -> dict:
    outfit_id = outfit["outfit_id"]
    character_id = queue.get("primary_character", "")
    video_id = f"{outfit_id}_wan27_base_001"
    prompt_path = prompts_root / prompt_filename(video_id)
    output_path = outputs_root / f"{video_id}.mp4"
    wardrobe_status = coalesce(result_record.get("status"), outfit.get("status"))

    return {
        "video_id": video_id,
        "character_id": character_id,
        "outfit_id": outfit_id,
        "wardrobe_status": wardrobe_status,
        "source_image_path": get_source_image_path(outfit, result_record),
        "prompt_path": str(prompt_path),
        "output_path": str(output_path),
        "model_family": MODEL_FAMILY,
        "status": TARGET_STATUS,
        "review_notes": "",
    }


def build_prompt(queue: dict, outfit: dict, record: dict) -> str:
    return PROMPT_TEMPLATE.format(
        source_image_path=record["source_image_path"],
        visual_package=outfit.get("visual_package", queue.get("visual_package", "")),
        thumbnail_style=outfit.get(
            "thumbnail_style", queue.get("thumbnail_style", "")
        ),
        character_id=record["character_id"],
        outfit_id=outfit["outfit_id"],
        description=outfit.get("description", ""),
        test_goal=outfit.get("test_goal", ""),
    ).strip()


def review_row(record: dict) -> str:
    return (
        f"| {record['video_id']} | {record['character_id']} | "
        f"{record['wardrobe_status']} | {record['status']} |  |  |  |  |  |  |  |"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create Wan 2.7 Replicate Web prompts and manifest from approved wardrobe images."
    )
    parser.add_argument("--job-id", default=DEFAULT_JOB_ID)
    parser.add_argument(
        "--queue-path",
        type=Path,
        default=None,
        help="Path to wardrobe_test_queue.json. Defaults to the production job queue.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT,
        help="Local repo metadata output root.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    queue_path = args.queue_path or default_queue_path(args.job_id)
    queue = load_json(queue_path)
    wardrobe_root = queue_path.parent
    output_root = args.output_root
    prompts_root = output_root / "replicate_inputs"
    manifest_path = output_root / "video_base_manifest.json"
    review_path = REPO_ROOT / "review" / "wan27_review.md"
    outputs_root = (
        PRODUCTION_ROOT / "04_video_jobs" / args.job_id / "video_base" / "replicate_outputs"
    )

    prompts_root.mkdir(parents=True, exist_ok=True)
    review_path.parent.mkdir(parents=True, exist_ok=True)

    videos = []
    skipped = []
    for outfit in queue.get("outfits", []):
        outfit_id = outfit.get("outfit_id", "")
        result_record = load_result_record(wardrobe_root, outfit_id)
        wardrobe_status = coalesce(result_record.get("status"), outfit.get("status"))

        if wardrobe_status not in VALID_STATUSES:
            raise ValueError(
                f"Invalid status for {outfit_id}: {wardrobe_status!r}. "
                f"Use one of: {', '.join(sorted(VALID_STATUSES))}"
            )

        if wardrobe_status not in ELIGIBLE_WARDROBE_STATUSES:
            skipped.append({"outfit_id": outfit_id, "status": wardrobe_status})
            continue

        record = build_video_record(queue, outfit, result_record, prompts_root, outputs_root)
        if not record["source_image_path"]:
            raise ValueError(
                f"{outfit_id} is {wardrobe_status}, but no wardrobe image path was found. "
                "Register a result_path or source_image_path before creating Wan 2.7 prompts."
            )

        prompt_path = Path(record["prompt_path"])
        prompt_path.write_text(build_prompt(queue, outfit, record) + "\n", encoding="utf-8")
        videos.append(record)

    manifest = {
        "job_id": queue.get("job_id", args.job_id),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "model_family": MODEL_FAMILY,
        "fallback_model_family": FALLBACK_MODEL_FAMILY,
        "source_queue_path": str(queue_path),
        "eligible_wardrobe_statuses": sorted(ELIGIBLE_WARDROBE_STATUSES),
        "official_status_values": sorted(VALID_STATUSES),
        "media_handling": "Metadata only. Do not copy generated images or video media into git.",
        "videos": videos,
        "skipped_outfits": skipped,
    }
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    review_rows = "\n".join(review_row(record) for record in videos)
    if not review_rows:
        review_rows = "| _No approved or needs_review wardrobe images yet._ |  |  |  |  |  |  |  |  |  |  |"
    review_path.write_text(
        REVIEW_TEMPLATE.format(
            job_id=queue.get("job_id", args.job_id),
            review_rows=review_rows,
        ).strip()
        + "\n",
        encoding="utf-8",
    )

    print(f"Queue read: {queue_path}")
    print(f"Prompts directory: {prompts_root}")
    print(f"Manifest written: {manifest_path}")
    print(f"Review written: {review_path}")
    print(f"Videos prepared: {len(videos)}")
    print(f"Skipped outfits: {len(skipped)}")


if __name__ == "__main__":
    main()
